#Dockerfile
FROM node:22-alpine

# Create app directory
WORKDIR /app

COPY package.json .

# Remmove existing yarn and install the latest version
RUN rm -rf /usr/local/bin/yarn /usr/local/bin/yarnpkg && npm install -g yarn

# Install app dependencies
RUN yarn install

# Bundle app source
COPY . .

CMD ["sh", "-c", "yarn build && yarn start"]
