services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bronotion-express-backend
    depends_on:
      - db
    ports:
      - "5433:5433"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bronotion
      DB_USER: admin
      DB_PASSWORD: admin
      PORT: 5433
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bronotion
    ports:
      - "5432:5432"
    